# Generated by Django 2.1.4 on 2018-12-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryID', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentID', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('added', models.DateTimeField(verbose_name='Added Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('width', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added', models.DateTimeField(verbose_name='Product published')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRanked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankingIntValue', models.IntegerField(default=5)),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('joined', models.DateField(verbose_name='Joined community')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='productranked',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.Ranking'),
        ),
        migrations.AddField(
            model_name='product',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.User'),
        ),
    ]
