# Generated by Django 2.1.4 on 2019-01-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dfrom', models.DateField(verbose_name='Pickup date')),
                ('Dto', models.DateField(verbose_name='Pickup date')),
                ('Dprice', models.IntegerField()),
            ],
        ),
    ]
