# Generated by Django 2.1.4 on 2018-12-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryID',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hobbies.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hobbies.User'),
            preserve_default=False,
        ),
    ]
