# Generated by Django 2.1.4 on 2019-01-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_pricecalc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecalc',
            name='Dto',
            field=models.DateField(verbose_name='Return date'),
        ),
    ]
