# Generated by Django 2.1.4 on 2018-12-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_auto_20181217_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productranked',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productranked',
            name='ranking',
        ),
        migrations.AddField(
            model_name='ranking',
            name='products',
            field=models.ManyToManyField(to='hobbies.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductRanked',
        ),
    ]
