# Generated by Django 2.1.4 on 2018-12-17 19:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0004_auto_20181217_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('spz', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(7)])),
                ('bought', models.DateField(verbose_name='Car was bought')),
                ('stk', models.DateField(verbose_name='STK expiracy')),
                ('nOAccidents', models.IntegerField()),
                ('pricePerDay', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('driverLicense', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)])),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('houseNumber', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('joined', models.DateField(verbose_name='Joined company')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('pickupD', models.DateField(verbose_name='Pickup date')),
                ('returnD', models.DateField(verbose_name='Return date')),
                ('cars', models.ManyToManyField(to='hobbies.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.Customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='products',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.Position'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.Model'),
        ),
    ]
