# Generated by Django 2.1.4 on 2019-01-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0006_reserv_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserv_form',
            new_name='ReservForm',
        ),
    ]
