# Generated by Django 2.1.4 on 2019-01-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0007_auto_20190106_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservForm',
            new_name='reserv_form',
        ),
    ]
