# Generated by Django 2.1.4 on 2019-01-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0010_auto_20190106_2319'),
        ('hobbies', '0008_auto_20190106_2136'),
    ]

    operations = [
    ]
